<template>
  <div class="page-head"><div><h1>{{role==='customer'?'我的咨询预约':'预约管理'}}</h1><p>{{subtitle}}</p></div><el-button v-if="role==='customer'" type="primary" icon="Plus" @click="openBooking">预约律师</el-button></div>
  <div class="panel"><div class="toolbar"><el-input v-model="query.keyword" placeholder="编号 / 姓名" clearable style="width:220px"/><el-select v-model="query.status" placeholder="全部状态" clearable style="width:150px"><el-option v-for="(x,i) in statusText" :key="i" :label="x" :value="i"/></el-select><el-button icon="Search" @click="load">查询</el-button></div>
  <div class="table-wrap"><el-table :data="rows"><el-table-column label="预约信息" min-width="185"><template #default="{row}"><b>{{row.appointmentNo}}</b><div class="muted">{{row.createTime}}</div></template></el-table-column><el-table-column prop="customerName" label="客户" width="110"/><el-table-column prop="lawyerName" label="律师" width="110"/><el-table-column prop="categoryName" label="咨询类别" width="120"/><el-table-column label="预约时段" min-width="220"><template #default="{row}">{{row.startTime}}<br><span class="muted">至 {{row.endTime}}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusType[row.status]">{{statusText[row.status]}}</el-tag></template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><template v-if="role==='admin'&&row.status===0"><el-button link type="success" @click="audit(row,1)">通过</el-button><el-button link type="danger" @click="audit(row,2)">驳回</el-button></template><el-button v-if="role==='customer'&&[0,1].includes(row.status)" link type="danger" @click="cancel(row)">取消</el-button><el-button v-if="role==='lawyer'&&row.status===1" link type="primary" @click="complete(row)">完成咨询</el-button><el-button v-if="role==='lawyer'&&[1,3].includes(row.status)&&!row.orderId" link type="warning" @click="openOrder(row)">创建订单</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" layout="total,prev,pager,next" :total="total" @current-change="load"/></div></div></div>
  <el-dialog v-model="bookVisible" title="预约法律咨询" width="700px"><el-form label-width="95px"><el-form-item label="咨询类别"><el-select v-model="booking.categoryId" style="width:100%" @change="booking.lawyerId=null"><el-option v-for="c in categories" :key="c.id" :label="`${c.name} · ¥${c.basePrice}/小时`" :value="c.id"/></el-select></el-form-item><div class="time-grid"><el-form-item label="开始时间"><el-date-picker v-model="booking.startTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="结束时间"><el-date-picker v-model="booking.endTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/></el-form-item></div><el-form-item><el-button icon="Search" @click="findLawyers">查找可预约律师</el-button></el-form-item><el-form-item label="选择律师"><div class="lawyer-cards"><div v-for="l in available" :key="l.id" :class="['lawyer-card',{selected:booking.lawyerId===l.id}]" @click="booking.lawyerId=l.id"><b>{{l.name}}</b><span>{{l.experienceYears}} 年经验 · ¥{{l.basePrice}}/小时</span><p>{{l.introduction}}</p></div><div v-if="!available.length" class="muted">请先设置类别和时间并查询</div></div></el-form-item><el-form-item label="咨询说明"><el-input v-model="booking.customerRemark" type="textarea" :rows="3" placeholder="简要描述需要咨询的问题"/></el-form-item></el-form><template #footer><el-button @click="bookVisible=false">取消</el-button><el-button type="primary" @click="submitBooking">提交预约</el-button></template></el-dialog>
  <el-dialog v-model="orderVisible" title="创建咨询收费订单" width="520px"><el-form label-width="100px"><el-form-item label="预约编号">{{order.appointmentNo}}</el-form-item><el-form-item label="咨询时长"><el-input-number v-model="order.durationMinutes" :min="15" :step="15"/> 分钟</el-form-item><el-form-item label="小时单价"><el-input-number v-model="order.unitPrice" :min="0" :step="50"/> 元</el-form-item><el-form-item label="预计金额"><b class="money">¥ {{(order.durationMinutes/60*order.unitPrice).toFixed(2)}}</b></el-form-item><el-form-item label="备注"><el-input v-model="order.remark" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="orderVisible=false">取消</el-button><el-button type="primary" @click="submitOrder">提交审核</el-button></template></el-dialog>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{appointmentApi,categoryApi,lawyerApi,orderApi}from'../api'
const role=localStorage.getItem('role'),rows=ref([]),total=ref(0),categories=ref([]),available=ref([]),bookVisible=ref(false),orderVisible=ref(false)
const query=reactive({pageNum:1,pageSize:10,status:null,keyword:''}),booking=reactive({categoryId:null,lawyerId:null,startTime:'',endTime:'',customerRemark:''}),order=reactive({})
const statusText=['待审核','已通过','已驳回','已完成','已取消'],statusType=['warning','success','danger','info','info'];const subtitle=computed(()=>role==='admin'?'审核客户提交的预约申请':role==='lawyer'?'查看已审核通过的咨询安排':'提交预约并跟踪审核状态')
async function load(){const r=await appointmentApi.list(query);rows.value=r.data.list;total.value=r.data.total}async function openBooking(){categories.value=(await categoryApi.all()).data;Object.assign(booking,{categoryId:null,lawyerId:null,startTime:'',endTime:'',customerRemark:''});available.value=[];bookVisible.value=true}
async function findLawyers(){if(!booking.categoryId||!booking.startTime||!booking.endTime)return ElMessage.warning('请先选择类别和时间');available.value=(await lawyerApi.available(booking)).data}
async function submitBooking(){if(!booking.lawyerId)return ElMessage.warning('请选择律师');await appointmentApi.add(booking);ElMessage.success('预约已提交');bookVisible.value=false;load()}
async function audit(r,status){const{value}=await ElMessageBox.prompt(status===1?'可填写审核说明':'请输入驳回原因','预约审核',{inputPlaceholder:'审核备注'});await appointmentApi.audit(r.id,{status,auditRemark:value});load()}
async function cancel(r){await ElMessageBox.confirm('确定取消此预约？','提示');await appointmentApi.cancel(r.id);load()}async function complete(r){await ElMessageBox.confirm('确认本次咨询已经完成？','提示');await appointmentApi.complete(r.id);load()}
function openOrder(r){Object.assign(order,{appointmentId:r.id,appointmentNo:r.appointmentNo,durationMinutes:60,unitPrice:300,remark:''});orderVisible.value=true}async function submitOrder(){await orderApi.add(order);ElMessage.success('订单已提交');orderVisible.value=false;load()}onMounted(load)
</script>
<style scoped>.time-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.lawyer-cards{width:100%;display:grid;grid-template-columns:1fr 1fr;gap:10px}.lawyer-card{padding:13px;border:1px solid #dfe7e3;border-radius:9px;cursor:pointer}.lawyer-card.selected{border-color:var(--jade);background:#f0f8f5}.lawyer-card b,.lawyer-card span{display:block}.lawyer-card span,.lawyer-card p{font-size:11px;color:#7f8d89}.lawyer-card p{margin:6px 0 0;line-height:1.5}</style>
