<template>
  <div class="page-head"><div><h1>{{admin?'律师管理':'律师名录'}}</h1><p>{{admin?'维护律师执业资料、服务类别与账号':'按专业方向了解平台执业律师'}}</p></div><el-button v-if="admin" type="primary" icon="Plus" @click="open()">新增律师</el-button></div>
  <div class="panel"><div class="toolbar"><el-input v-model="query.name" placeholder="律师姓名" clearable style="width:200px"/><el-select v-model="query.categoryId" placeholder="咨询类别" clearable style="width:170px"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select><el-button icon="Search" @click="load">查询</el-button></div>
  <div class="table-wrap"><el-table :data="rows"><el-table-column label="律师" width="150"><template #default="{row}"><b>{{row.name}}</b><div class="muted">{{row.gender}} · {{row.experienceYears}}年经验</div></template></el-table-column><el-table-column prop="licenseNo" label="执业证号" width="150"/><el-table-column prop="categoryNames" label="专业方向" min-width="190"><template #default="{row}"><el-tag v-for="x in (row.categoryNames||'').split(',').filter(Boolean)" :key="x" effect="plain" style="margin:2px">{{x}}</el-tag></template></el-table-column><el-table-column prop="introduction" label="简介" min-width="260" show-overflow-tooltip/><el-table-column prop="phone" label="联系电话" width="130"/><el-table-column v-if="admin" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status===1?'success':'info'">{{row.status===1?'可预约':'停用'}}</el-tag></template></el-table-column><el-table-column v-if="admin" label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" layout="total,prev,pager,next" :total="total" @current-change="load"/></div></div></div>
  <el-dialog v-model="visible" :title="form.id?'编辑律师':'新增律师及账号'" width="680px"><el-form :model="form" label-width="90px"><div class="form-grid"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><el-form-item label="性别"><el-select v-model="form.gender"><el-option label="男" value="男"/><el-option label="女" value="女"/></el-select></el-form-item><el-form-item label="联系电话"><el-input v-model="form.phone"/></el-form-item><el-form-item label="执业证号"><el-input v-model="form.licenseNo"/></el-form-item><el-form-item label="从业年限"><el-input-number v-model="form.experienceYears" :min="0"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0"/></el-form-item><el-form-item v-if="!form.id" label="登录账号"><el-input v-model="form.username"/></el-form-item><el-form-item v-if="!form.id" label="初始密码"><el-input v-model="form.password"/></el-form-item></div><el-form-item label="服务类别"><el-select v-model="form.categoryIds" multiple style="width:100%"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="个人简介"><el-input v-model="form.introduction" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup>
import { onMounted,reactive,ref } from 'vue';import {ElMessage,ElMessageBox} from 'element-plus';import{categoryApi,lawyerApi}from'../api'
const admin=localStorage.getItem('role')==='admin',rows=ref([]),total=ref(0),categories=ref([]),visible=ref(false),query=reactive({pageNum:1,pageSize:10,name:'',categoryId:null}),form=reactive({})
async function load(){const r=await lawyerApi.list(query);rows.value=r.data.list;total.value=r.data.total}
function open(row={}){Object.assign(form,{id:null,name:'',gender:'男',phone:'',licenseNo:'',experienceYears:0,introduction:'',status:1,username:'',password:'123456',categoryIds:[]},row,{categoryIds:(row.categoryIds||'').toString().split(',').filter(Boolean).map(Number)});visible.value=true}
async function save(){if(!form.name||!form.phone||!form.licenseNo)return ElMessage.warning('请填写姓名、电话和执业证号');await(form.id?lawyerApi.update(form):lawyerApi.add(form));ElMessage.success('保存成功');visible.value=false;load()}
async function remove(row){await ElMessageBox.confirm(`确定删除${row.name}？`,'提示',{type:'warning'});await lawyerApi.remove(row.id);load()}onMounted(async()=>{categories.value=(await categoryApi.all()).data;load()})
</script>
<style scoped>.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}</style>
