<template>
  <div class="page-head"><div><h1>{{role==='customer'?'我的账单':'咨询收费订单'}}</h1><p>订单金额由咨询时长与小时单价自动核算</p></div></div>
  <div class="panel"><div class="toolbar"><el-input v-model="query.keyword" placeholder="订单编号 / 姓名" clearable style="width:230px"/><el-select v-model="query.status" placeholder="全部状态" clearable style="width:150px"><el-option v-for="(x,i) in texts" :key="i" :label="x" :value="i"/></el-select><el-button @click="load">查询</el-button></div><div class="table-wrap"><el-table :data="rows"><el-table-column label="订单信息" min-width="190"><template #default="{row}"><b>{{row.orderNo}}</b><div class="muted">{{row.orderTime}}</div></template></el-table-column><el-table-column prop="lawyerName" label="律师" width="110"/><el-table-column prop="customerName" label="客户" width="110"/><el-table-column prop="categoryName" label="类别" width="120"/><el-table-column label="计费" width="160"><template #default="{row}">{{row.durationMinutes}}分钟 × ¥{{row.unitPrice}}/时</template></el-table-column><el-table-column label="金额" width="120"><template #default="{row}"><span class="money">¥ {{row.totalAmount}}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="types[row.status]">{{texts[row.status]}}</el-tag></template></el-table-column><el-table-column v-if="role==='admin'" label="操作" width="190"><template #default="{row}"><template v-if="row.status===0"><el-button link type="success" @click="audit(row,1)">通过</el-button><el-button link type="danger" @click="audit(row,2)">驳回</el-button></template><el-button v-if="row.status===1" link type="primary" @click="audit(row,3)">确认收款</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" layout="total,prev,pager,next" :total="total" @current-change="load"/></div></div></div>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import{ElMessageBox}from'element-plus';import{orderApi}from'../api'
const role=localStorage.getItem('role'),rows=ref([]),total=ref(0),query=reactive({pageNum:1,pageSize:10,status:null,keyword:''}),texts=['待审核','审核通过','已驳回','已收费','已取消'],types=['warning','success','danger','success','info']
async function load(){const r=await orderApi.list(query);rows.value=r.data.list;total.value=r.data.total}async function audit(r,status){let remark='';if(status!==3){const p=await ElMessageBox.prompt(status===1?'确认订单信息无误？':'请输入驳回原因','订单审核');remark=p.value}await orderApi.audit(r.id,{status,auditRemark:remark});load()}onMounted(load)
</script>
