<template>
  <div class="page-head"><div><h1>{{lawyer?'资料修改申请':'律师资料审核'}}</h1><p>{{lawyer?'修改内容需经管理员审核后生效':'对比原资料与拟修改内容，完成审核'}}</p></div><el-button v-if="lawyer" type="primary" icon="Edit" @click="open">提交修改申请</el-button></div>
  <div class="panel"><div class="toolbar"><el-select v-model="query.status" placeholder="全部状态" clearable style="width:150px"><el-option label="待审核" :value="0"/><el-option label="已通过" :value="1"/><el-option label="已驳回" :value="2"/></el-select><el-button @click="load">查询</el-button></div><div class="table-wrap"><el-table :data="rows"><el-table-column prop="lawyerName" label="律师" width="120"/><el-table-column label="资料变更" min-width="380"><template #default="{row}"><div class="change"><span>姓名</span>{{row.oldName||row.lawyerName}} → <b>{{row.applyName}}</b></div><div class="change"><span>电话</span>{{row.oldPhone}} → <b>{{row.applyPhone}}</b></div><div class="change"><span>类别</span>{{row.oldCategoryNames||'—'}} → <b>{{categoryNames(row.applyCategoryIds)}}</b></div></template></el-table-column><el-table-column prop="createTime" label="提交时间" width="170"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="['warning','success','danger'][row.status]">{{['待审核','已通过','已驳回'][row.status]}}</el-tag></template></el-table-column><el-table-column v-if="!lawyer" label="操作" width="140"><template #default="{row}"><template v-if="row.status===0"><el-button link type="success" @click="audit(row,1)">通过</el-button><el-button link type="danger" @click="audit(row,2)">驳回</el-button></template></template></el-table-column></el-table><div class="pagination"><el-pagination v-model:current-page="query.pageNum" layout="total,prev,pager,next" :total="total" @current-change="load"/></div></div></div>
  <el-dialog v-model="visible" title="律师资料修改申请" width="600px"><el-alert title="提交后不会立即更新正式资料，管理员审核通过后生效。" type="info" :closable="false" style="margin-bottom:18px"/><el-form label-width="90px"><el-form-item label="姓名"><el-input v-model="form.applyName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.applyPhone"/></el-form-item><el-form-item label="咨询类别"><el-select v-model="form.categoryIds" multiple style="width:100%"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="个人简介"><el-input v-model="form.applyIntroduction" type="textarea" :rows="4"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="submit">提交审核</el-button></template></el-dialog>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import{ElMessage,ElMessageBox}from'element-plus';import{applyApi,categoryApi,lawyerApi}from'../api'
const lawyer=localStorage.getItem('role')==='lawyer',rows=ref([]),total=ref(0),categories=ref([]),visible=ref(false),query=reactive({pageNum:1,pageSize:10,status:null}),form=reactive({})
async function load(){const r=await applyApi.list(query);rows.value=r.data.list;total.value=r.data.total}function categoryNames(ids){return(ids||'').split(',').map(id=>categories.value.find(c=>c.id===Number(id))?.name).filter(Boolean).join('、')||'—'}
async function open(){const[p,c]=await Promise.all([lawyerApi.profile(),categoryApi.all()]);categories.value=c.data;Object.assign(form,{applyName:p.data.name,applyPhone:p.data.phone,applyIntroduction:p.data.introduction,categoryIds:(p.data.categoryIds||'').toString().split(',').filter(Boolean).map(Number)});visible.value=true}
async function submit(){await applyApi.submit(form);ElMessage.success('申请已提交');visible.value=false;load()}async function audit(r,status){const p=await ElMessageBox.prompt(status===1?'确认通过该资料修改？':'请输入驳回原因','资料审核');await applyApi.audit(r.id,{status,auditRemark:p.value});load()}
onMounted(async()=>{categories.value=(await categoryApi.all()).data;load()})
</script>
<style scoped>.change{margin:5px 0;color:#72807c}.change span{display:inline-block;width:45px;color:#9aa4a1}.change b{color:var(--forest)}</style>
