<template>
  <div class="page-head"><div><h1>空闲时间</h1><p>维护律师可接受预约的服务时间段</p></div><el-button type="primary" icon="Plus" @click="open()">添加时间段</el-button></div>
  <div class="panel"><div class="toolbar"><el-select v-if="admin" v-model="query.lawyerId" placeholder="全部律师" clearable style="width:180px"><el-option v-for="l in lawyers" :key="l.id" :label="l.name" :value="l.id"/></el-select><el-date-picker v-model="query.fromTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="从此时间起"/><el-button @click="load">查询</el-button></div><div class="table-wrap"><el-table :data="rows"><el-table-column prop="lawyerName" label="律师" width="130"/><el-table-column prop="startTime" label="开始时间" width="190"/><el-table-column prop="endTime" label="结束时间" width="190"/><el-table-column prop="remark" label="备注"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="['success','warning','info'][row.status]">{{['空闲','已预约','停诊'][row.status]}}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></div></div>
  <el-dialog v-model="visible" :title="form.id?'编辑时间段':'添加空闲时间'" width="540px"><el-form label-width="90px"><el-form-item v-if="admin" label="律师"><el-select v-model="form.lawyerId" style="width:100%"><el-option v-for="l in lawyers" :key="l.id" :label="l.name" :value="l.id"/></el-select></el-form-item><el-form-item label="开始时间"><el-date-picker v-model="form.startTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="结束时间"><el-date-picker v-model="form.endTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" style="width:100%"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio :value="0">空闲</el-radio><el-radio :value="2">停诊</el-radio></el-radio-group></el-form-item><el-form-item label="备注"><el-input v-model="form.remark"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
</template>
<script setup>
import{onMounted,reactive,ref}from'vue';import{ElMessageBox}from'element-plus';import{lawyerApi,scheduleApi}from'../api'
const admin=localStorage.getItem('role')==='admin',rows=ref([]),lawyers=ref([]),visible=ref(false),query=reactive({lawyerId:null,fromTime:''}),form=reactive({})
async function load(){rows.value=(await scheduleApi.list(query)).data}function open(r={}){Object.assign(form,{id:null,lawyerId:query.lawyerId,startTime:'',endTime:'',status:0,remark:''},r);visible.value=true}
async function save(){await(form.id?scheduleApi.update(form):scheduleApi.add(form));visible.value=false;load()}async function remove(r){await ElMessageBox.confirm('确定删除此时间段？','提示');await scheduleApi.remove(r.id);load()}
onMounted(async()=>{if(admin)lawyers.value=(await lawyerApi.list({pageNum:1,pageSize:500})).data.list;load()})
</script>
